devices:
  - name: PCL.FSJ.DC01.AGG01
    host: 100.127.0.13
    device_type: cisco_ios
    username: july
    password: jks!034L

  - name: PCL.FSJ.DC01.AGG02
    host: 100.127.0.14
    device_type: cisco_ios
    username: july
    password: jks!034L

  - name: PCL.FSJ.BLTC.RTR01
    host: 192.168.176.1
    device_type: cisco_ios
    username: july
    password: jks!034L

  - name: PCL.FSJ.P109.RTR01
    host: 192.168.160.1
    device_type: cisco_ios
    username: july
    password: jks!034L

  - name: PCL.FSJ.C46C.RTR01
    host: 192.168.200.1
    device_type: cisco_ios
    username: july
    password: jks!034L

  - name: PCL.FSJ.INGA.RTR01
    host: 192.168.0.1
    device_type: cisco_ios
    username: july
    password: jks!034L

  - name: PCL.FSJ.CFCK.RTR01
    host: 192.168.2.1
    device_type: cisco_ios
    username: july
    password: jks!034L

  - name: PCL.FSJ.MTVW.RTR01
    host: 192.168.64.1
    device_type: cisco_ios
    username: july
    password: jks!034L

  - name: PCL.FSJ.DGPK.RTR01
    host: 192.168.128.1
    device_type: cisco_ios
    username: july
    password: jks!034L

  - name: PCL.FSJ.BEAR.RTR01
    host: 192.168.144.1
    device_type: cisco_ios
    username: july
    password: jks!034L

  - name: PCL.FSJ.PKMT.RTR01
    host: 192.168.96.1
    device_type: cisco_ios
    username: july
    password: jks!034L

  - name: PCL.FSJ.MCKN.RTR01
    host: 192.168.192.1
    device_type: cisco_ios
    username: july
    password: jks!034L

